### ISSUE TITLE
FastLED 3.1 with IntervalTimers on Teensy 3.1

### ISSUE THREAD

**Issue by jamescarruthers** [FastLED/FastLED#122]
I get corrupted output (only the first three LEDs showing out of 24) if I use IntervalTimer set at an interval of 100 on the Teensy platform.

If I increase the interval I get something more approaching what I am expecting — but it's still corrupted.

James

**Comment by focalintent** [comment]
It takes 30us to write out a ws2812 led, if you are firing an interrupt every 100us, and if your interrupt takes more than 10us to run the library is going to punt writing out the current frame (which is why you still see cut off a frame with higher intervals), hence your only 3 leds showing up. 

You need to make your function called by the timer as lightweight as possible, or switch to an LED chipset that doesn't have issues with being interrupted (apa102, lpd8806), or if you don't mind the memory hit, use FastLED's OctoWS2811 (then your leds have to be on one of the 8 OctoWS2811 pins).

**Comment by focalintent** [comment]
Alternatively, If you show me the code you're running on your interval timer I can help you trim down its overhead.

**Comment by jamescarruthers** [comment]
Ahhh, of course!

Thanks Dan, I'm being an idiot.
