### ISSUE TITLE
NO_CORRECTION define is used for two different purposes

### ISSUE THREAD

**Issue by ben-xo** [FastLED/FastLED#1263]
I noticed that NO_CORRECTION is used both [here](https://github.com/FastLED/FastLED/blob/5cc17b2be88982eb34b1998de22b83fee56d4f07/src/platforms/avr/clockless_trinket.h#L90) and [here](https://github.com/FastLED/FastLED/blob/5cc17b2be88982eb34b1998de22b83fee56d4f07/src/controller.h#L151) for different purposes.

The first one is to turn off clock-correction in AVR (which you might want to do if you have got interrupts working) and the second is for color-correction.

Given that this is a compatibility break I'd suggest renaming both defines (NO_COLOR_CORRECTION / NO_CLOCK_CORRECTION) and checking both the new name and the old name NO_CORRECTION (or maybe print out a warning)

**Comment by kriegsman** [comment]
Finding this is a good catch; thank you. 
I like the idea of checking both the new and old name.  I don't think a warning would be net-helpful; the people who need to separately control the two settings will figure it out, and the people who don't need to do that probably shouldn't be bothered with a new warning on their existing code.  But: I want to think about that a little bit, because in general I do like giving informative warnings to people who might will benefit from seeing them.

**Comment by ben-xo** [comment]
@kriegsman is there a project chat / IRC / Slack / whatever? I know the reddit, but that doesn't seem like a chat venue for project discussion

**Comment by ben-xo** [comment]
Raised a PR for this. #1271

**Comment by ben-xo** [comment]
Closed as my PR was merged
