### ISSUE TITLE
Not possibile to use FastLED inside a custom Class

### ISSUE THREAD

**Issue by Sladerix** [FastLED/FastLED#1503]
Hi everyone, I noticed an annoying thing.

I made a class for my code where I use FastLED.
My calss has its constructor, where I want to initialize the FastLED library so...

HPP FILE
```
[...]
    private:
        CRGB *leds;
        uint8_t DATA_PIN;
        int NUM_LEDS;
[...]
```

CPP FILE
```
LedManager::LedManager(int number_of_leds, uint8_t data_pin)
{
  leds = new CRGB[NUM_LEDS];
  NUM_LEDS = number_of_leds;
  DATA_PIN = data_pin;

  FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);
  FastLED.clear();
  FastLED.show();
}
```

This does not work because it seems that the "addLeds" function accept only the "native" data types...
I explain better..

uint8_t DATA_PIN ✅
uint8_t LedManager::DATAPIN ❌

or using the #define but in this way I cannot set them in the Arduino setup()

**Comment by zackees** [comment]
You are falling into a trap that a lot of people fall into, which is to approach MCU programming like you would a large scale C++ program. The trap includes encapsulating everything into a class and member variables. This has a lot of problems as people tend to then **statically initialize these class instances** and they get really weird undefined behavior.

A better way to approach MCU programming is to think of it like a C program with C++ features. Most of the classes you want to make anyway will only have exactly one instance. So it makes sense to encapsulate them not at the class level but at the cpp file level.

That means everything is global inside of the cpp module. Have your data as POD data, statically initialized. If you want to have class that initializes then have a setup() function that you call for that module. So for example, if you have a `gfx.h` then use `gfx_setup()` and `gfx_run()`. Don't use static initializers of non pod data, as those will run before the program is fully and properly initialized. This has been a big foot gun for me and results in undefined behavior especially as you try and switch micros and suddenly your code no longer works because the arduino API used by a particular platform will vary **wildly**. For example, check out out how the ESP32 launches a thread so that Arduino `loop()` is called.

So in your case, you have Fastled and CRGB array as member variables of an aggregate class. Instead have the CRGB as a static pod data type in your cpp module. You can zero initialize it like this `static CRGB led_array[NUM_LEDS] = {0};` or memset to zero in your setup function. Your gfx_setup() function well then initialize the FastLED and add the leds to it.

Additionally, for const values you can just use the good old `#define`. If you want to centralize all your defines then put them in a `defs.h`. If you still have problems after this then post what they are and I can help you.

**Comment by zackees** [comment]
As an update, I've come up with a theoretical scheme that allows constructors for each chipset + pin to be defined.

Essentially it's a giant switch statement that combines chipset multiplied by pin type.

Bad news, FastLED is designed around compile asserts. And different boards have different pins that are valid vs invalid.

So a cross platform dynamic constructor table doesn't work without template specialization magic to determine if the pin desired is valid or not, and this will be necessary to push to all parts of the codebase for all platform types.

The good news is that for any particular board type this dynamic table can be custom specified in client code. But making it work everywhere is a giant non trivial problem.
