### ISSUE TITLE
SPI_CLOCK and SPI_DATA macros' names are excessively generic

### ISSUE THREAD

**Issue by OoDeLally** [FastLED/FastLED#1565]
I am using another library (a driver for MC2515) that uses a local variable named `SPI_CLOCK` (expressing the frequency of the clock).

Because FastLED `#define`s a `SPI_CLOCK` macro, it creates an unwanted substitution leading to a parsing error.

Cpp macros' namespace is global, so it is good practice to increase the specificity of macro names to avoid pollution.

My opinion is that `SPI_CLOCK` (and `SPI_DATA` by the same) is not specific enough and inevitably creates conflicts with other libraries.

An easy fix is to simply rename is `SPI_DATA_PIN`, which would be a first step. But something with a prefix (e.g. `FASTLED_SPI_DATA`) would be ideal.

**Comment by zackees** [comment]
I'm sorry but in this case you'll have to not include fast led where you include your driver and use an abstraction layer to access the functionality in the cpp file. Usually this is done anyway to get a nice code barrier and hide driver code from colliding into each other like you are experiencing now.

We can't change it because too much code relies on that name being that name. It would break too many users.
