### ISSUE TITLE
Support TLC5940

### ISSUE THREAD

**Issue by sfranzyshen** [FastLED/FastLED#18]
I would like to help to get the TLC5940 support started ... but I am confused as to how to. Is there anyone else who is working on this (tlc5940) support or another chip that I could see how adding a chip is done? Is there a mailing list or forum where developers meet?

**Comment by pcharest2000** [comment]
focalintent and  kriegsman:  The tlc5940 can be used in 8 bit without mapping to 16 bit.  The trick is to fill the 12 bit data with 8 bit pwm value and then trigger the  blank signal when you have saturated the 8 bit value.  I have done this on several of my project on Avr and Arm cortex.  This consumes very little resources since the GSCLK and Blank signal are all generated thru PWM.  Also using SPI on AVR when  sending one byte you have about 18 cycles  between SPI send.  This gives just enough time to built the "12 bit" packed stream between SPI send.   The TLC5940 could be supported without touching the base code color functions  of FastLed, of course you don't get 12 bit resolution on the TLC 5940  but who really cares?  I do not understand why such a high resolution was used for this IC by TI,  I don't think the normal human can spot the difference between 8 bit and 12 bit color value....

Phil

**Comment by focalintent** [comment]
Doing more research into the TLC5940, and I'm inclined to close this off and _not_ add support for the TCL5940 to the library, for multiple reasons:

* there is no consistent RGB ordering, requiring users to wire their leds up in a predictable fashion (aka, this will be a support nightmare for me of dealing with people who wire up their leds in strange ways)
* it requires coordinating latch/blanking pins to lock data in, this adds to the number of pins that need to be part of the configuration and may also require setting up interrupts to handle things properly (I'm fairly uninterested in having FastLED rely on interrupts for functionality, especially at an led chipset level - there's over a half dozen low level architectures supported, I don't want to have to re-implement tlc5940 specific handling for each of them)
* and the one that is the real killer - the TLC5940 does not do its own PWM, it requires an external clock to generate the timing signal.  This requires generating a high speed PWM pulse from the MCU to drive the data.  Not all the MCU's supported by FastLED even have hardware PWM as an option (for example, the nrf51822 used by the rfduino).  This falls into a similar line as the interrupt handling for the blanking/latching.  Not something that I want to repeat an implementation of a half dozen for supporting one chipset.

I killed off support for the LPD6803 because I didn't want to have to drive a clock line from the MCU constantly.  As far as I can tell, other than 12-bit pwm support, there isn't any driving reason that I can think of to support the TLC5940 going forward.  

Folks who want to use the TLC5940 w/FastLED's math/color functions can use FastLED to do all the pre-writing data out manipulation, then use something like the TLC5940 library for actually driving the leds - https://code.google.com/p/tlc5940arduino/ 

Unless someone can give me a good, compelling reason to reconsider, I'm going to close this ticket in a few days.

**Comment by pcharest2000** [comment]
Daniel,

I completely agree with your assessment.    I don't want to sound like an ass but for the average user the TL5940 is complex to wire up compared to current supported led drivers by fastled (1,2,3 wire)...

Phil

**Comment by focalintent** [comment]
Not going to support the TLC* chipsets - I ripped out host-drive PWM support years ago from FastLED (rip, LPD6803) and have no interest in putting it back in.

**Comment by mihow** [comment]
After doing more reading, turns out the TLC5947 and TLC59711 do _not_ require external clocks. Only the TLC5940 requires an external clock, and is different in multiple ways. Here is one thread about the 3 chips: https://forums.adafruit.com/viewtopic.php?f=19&t=66635&sid=b2bf261201c64729db7895e4481d23e7#p337802

**Comment by focalintent** [comment]
Yeah - I found that and now have 59747 and 59711 support planned - now I just need the time and space to do it (in part, I'm waiting to implement more major chipsets until I finish some internal juggling in the library, which i'm hoping to get to next week)

**Comment by mihow** [comment]
Ah good to hear. I'm using currently using a few TLC5947s with the basic Adafruit library, but would love to try FastLED and some of the wave functions that happens. Great work overall!

**Comment by heX16** [comment]
LPD6803 do not require external clocks! (external clock is the optional mode of this chip).
I add [support LPD6803](https://github.com/FastLED/FastLED/pull/701) and its work perfect with leds from aliexpress (and with out external clock).

**Comment by nerdyscout** [comment]
according to the [chipset reference](https://github.com/FastLED/FastLED/wiki/Chipset-reference#upcoming) TLC5947 support is planned, but I guess this dead thread here is more correct... correct?
