### ISSUE TITLE
scale16by8 silently relies on integer overflows?

### ISSUE THREAD

**Issue by Be-ing** [FastLED/FastLED#1821]
When [porting the pseudo-13-bit gamma correction algorithm to Rust](https://github.com/smart-leds-rs/apa102-spi-rs/pull/15), I noticed that [`scale16by8`](https://github.com/FastLED/FastLED/blob/d5aaf65be19782f3e52b8b0fe38778f14376a293/src/lib8tion/scale8.h#L476) silently relies on integer overflows to work. The values passed to that function in its tests overflow the multiplication of `i * (1 + ((uint16_t)scale))` before the bitshift is applied. A `uint32_t` value is needed to hold the value of that multiplication before the `>> 8`.

I don't understand how this works because unsigned integer overflow in C++ is specified to wrap, but using Rust's `wrapping_mul` function to replicate that behavior fails the tests. Does overflowing an unsigned integer smaller than `size_t` silently just work like a `size_t` or something...?

**Comment by zackees** [comment]
oh geez. It's possible that earlier checks are preventing degenerate values from reaching the scale function. I do have unit tests, but yes, those tests run on a native device. It's totally possible it has degenerate values on 8 bit avrs

**Comment by sutaburosu** [comment]
As I understand it, AVR is the only platform FastLED supports with a word size less than 32-bits and AVR has assembly variants of these functions so there should be no bug evident in FastLED. 

I guess rather than relying on implicit promotion to uint, the C implementation should be made explicitly 32-bits just like the scale16() variant.
