### ISSUE TITLE
SparkCore support

### ISSUE THREAD

**Issue by focalintent** [FastLED/FastLED#22]
Implement pin and hardware spi support for the STM32 in the SparkCore.

**Comment by embedded-creations** [comment]
I don't think anything has changed since Mark said he was waiting for multiple file library support.  
https://community.spark.io/t/update-on-library-support-eg-fastled/4252/17

@pkourany Do you have any inside knowledge on multi-file library support?  Are there any workarounds that don't require bringing everything into one file?  Does Spark CLI support multi-file libraries?  When I looked into it I thought even CLI was limited to single file libraries but I'd love to be wrong on this.

**Comment by focalintent** [comment]
At the moment it is just me getting to block the time aside to do the low level porting bits to the STM32 processor.  I've got some time carved out for next week that I should be able to do this in.  (I also believe I have another STM32 based board here that I can (ab)use for doing the hardware bits of the port, and then figure out spark core's library support later on.

**Comment by focalintent** [comment]
(The nrf51822 ended up getting higher priority for a port, mostly because I had a paid contract that was based on the nrf51822)

**Comment by embedded-creations** [comment]
Sounds good Daniel, I'm really looking forward to the Spark Photon being released.  I think it will make a great platform for connected LED projects.

**Comment by focalintent** [comment]
Spark core is in there, now.
