### ISSUE TITLE
Latest version(s) of FastLED not working on particle / sparkcore

### ISSUE THREAD

**Issue by shlomozippel** [FastLED/FastLED#252]
FastLED version 3.1.3 on sparkcore gives me compile errors related to SPI. It seems there is a conflict between the macro SPI (#define SPI __fetch_global_SPI()) and the typedef SPI (typedef SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> SPI;)

This problem didn't exist in 3.1 a few weeks ago.

Thanks!

**Comment by focalintent** [comment]
It's because particle lib 0.4.9 (or 0.9.4?) was just pushed which does a stupid thing (#define SPI) which breaks all the places where I have well scoped typedefs named SPI. 

The solution (until they fix their shit) is to add #undef SPI before including FastLED.  (I'm wary of putting that in the library because it will break folks who want to use SPI as well as FastLED - I'm hoping particle fixes their stuff)

**Comment by shlomozippel** [comment]
Thanks!
