### ISSUE TITLE
Delete a Controller Instance

### ISSUE THREAD

**Issue by Pecacheu** [FastLED/FastLED#255]
Okay, I have another question.

So, I have the Arduino Zero talking through Serial to a controlling computer. I need to be able to change the properties (speed, pin numbers, but most importantly LED count) that I specified in `addLeds`.

Is there some sort of "removeLeds" or something, so I can delete and re-initialize the LEDs? I didn't see anything that looked like that in the documentation.

**Comment by focalintent** [comment]
No, there isn't.  Things like pin numbers and clock speed are baked in at compile time - they aren't changeable at run time, and since the controllers are all statically allocated if you're using addLeds, there really isn't a mechanism to remove them.  (This is not really a use case that the library is designed for, and in fact many of its optimizations work against it).

You can, however, change the number of leds at run time - see http://fastled.io/docs/3.1/class_c_l_e_d_controller.html#a5b08378b29f92c5def65175ec5334037 

You can either save a reference to a controller object ( addLeds returns a reference to CLEDController, which is the base type of all the various led controllers), or you can use the [] operator on FastLED to get reference to a specific controller (e.g. ```FastLED[0]``` is the CLEDController object from the first call to addLeds, ```FastLED[1]``` is the second, etc... - so you could possibly do ```FastLED[0].setLeds(leds, newCountOfLEDs);``` )
