### ISSUE TITLE
How to store current values and average them out

### ISSUE THREAD

**Issue by yoxalld** [FastLED/FastLED#279]
I am looking for a way to keep track of the past rgb values for each led and then get an average value for them. I am not sure how to access/store the values to then be able to average them. I found this from the documentation but it just makes the LEDS freeze up and doesn't give me any values. 
`Serial.readBytes( (char*)(&leds[i]), 3); // read three bytes: r, g, and b.`

I am still very new to arduino and working with this programming language so if someone could point me in the right direction that would be great!

Thanks!

**Comment by focalintent** [comment]
It'd be better to ask a question like that on the g+ group - http://fastled.io/+ -- far more people watch that group and you'll likely get a wider range of advice and help - I really try to leave the github issues for bug reports and feature requests.

What you've written up there though is an attempt to read 3 bytes of values from the serial input - if you aren't sending any data over the serial port, it's just going to wait forever, which is why things freeze up.
