### ISSUE TITLE
Reversing every second line in LED matrix

### ISSUE THREAD

**Issue by olesk75** [FastLED/FastLED#34]
Hi and thanks for the awesome library!

I'm a little hesitant to put this forward, as I might belong to a small minority, but I thought I'd at least mention it and see what you think.

I've bought of of these: https://www.kickstarter.com/projects/311408456/rgb-123-led-matrices

In my case a 16x16 matrix of 256 WS2812B LEDs. Works wonderfully with FastLED with one minor issue: every second row is reversed. This due to the LEDs being wired in a zigzag pattern in the matrix, where led15 is on the first row in the last column on the right, while led16 is one row below in the same column, and led17 one column to the left - you get the idea.

As I let the Arduino (and later the Spark Core whenever FastLED supports it) simply receive data over serial or WiFi from a PC (it "streams" live) I've moved the heavy lifting of reversing every second line to my Python code on the PC in stead of wasting precious cycles on the Arduino. However, I was thinking that I'm probably not the only one that might have LEDs wired in a zigzag pattern, so perhaps this is something for FastLED? 

OJ - no relation

**Comment by IIroobixII** [comment]
@focalintent I wasn't able to find your video, this might be a dead thread and if it's not too much could you dig up that link as it would answer my question I believe, thanks

**Comment by focalintent** [comment]
Not sure what video you're referring to - or for that matter the question you'd like answered :)

**Comment by IIroobixII** [comment]
I'm sorry for the misunderstanding but hopefully you are still able to help me out as i would greatly appreciate it. I was trying to find help on my column matrix serpentine raster matrix I built (very noob 2nd project) 8x17 neopixel and found a comment of yours from 2 years ago quoted "I posted a basic xy matrix class to there at some point."  and I thought you had meant you had posted a tutorial/class instead of the actual "class" function as I think you meant on the g+ community. I am trying to treat my matrix as a two dimensional display and I don't fully grasp how to use a 2d array quite yet as I am trying to get something to scroll and was just told that " to transfer the matrix defining the display you want with a one column offset into the LED buffer. This shifts the whole pattern over to the right or left depending on the sign of the offset. " because as of now I am just creating text by the "setpixelcolor" function with each led individually.
________________________________

**Comment by focalintent** [comment]
It sounds like you're using the neopixel library - which I generally don't use - if you want specifics on how to scroll a 2D matrix I'd say ask on the g+ group for FastLED if you're using FastLED (http://fastled.io/+) or on adafruit's forums if you're using the neopixel library.

**Comment by jasoncoon** [comment]
This is possible using the kMatrixSerpentineLayout variable in the XYMatrix demo: https://github.com/FastLED/FastLED/blob/master/examples/XYMatrix/XYMatrix.ino

Another option is this library used with FastLED: https://github.com/AaronLiddiment/LEDMatrix
