### ISSUE TITLE
Anything but RGB Colour Order causes compile error (Feather M0, APA102, Arduino 1.6.11, FastLED 3.1.5)

### ISSUE THREAD

**Issue by happyinmotion** [FastLED/FastLED#365]
I'm setting up an APA102 strip to run from a Feather M0 WiFi (ATSAMD21 + ATWINC1500), using the 1.6.11 IDE and FastLED 3.1.5, with a MOSFET in there to control power to the strip. First job after getting the LEDs to light is check the colour order.

RGBCalibrate runs just fine with the RGB colour order. The LED strip shows 1 Blue, 2 Green, 3 Red. Ok, so set it to BGR. And the code fails to compile. Error is:

[http://pastebin.com/sPppmfg3](http://pastebin.com/sPppmfg3)

Odd.

Checking other colour orders gives:
RBG - compiles without complaint, but code doesn't run.
GRB - same compile error as above.
GBR - same compile error as above.
BRG - same compile error as above.

The code I'm running is RGBCalibrate with a minor change to turn on the MOSFET:
[http://pastebin.com/mQtVBuv9](http://pastebin.com/mQtVBuv9)

(Also, trivially, this is FastLED version 3.1.5 and library.properties has "version=3.1.5" but FastLED.h has the message "pragma message "FastLED version 3.001.005". Is there a reason for that or is that just an oversight?)

**Comment by focalintent** [comment]
The problem is that APA102 requires a clock _and_ data pin:

```FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS);```

The compiler is interpreting the value that you put in for COLOR_ORDER as the pin for the clock - some of the integer values for color orders are high enough that they would show off as an invalid pin.

As for the pragma output, the leading zeros is just a printing convention on output - it's still 3.1.5 in all the places.

**Comment by happyinmotion** [comment]
Ah, cheers for spotting that.

Putting:
    FastLED.addLeds<LED_TYPE,DATA_PIN,CLK_PIN,COLOR_ORDER>(leds, NUM_LEDS);
Works just fine and BGR it is.
