### ISSUE TITLE
Compilation error using an example.

### ISSUE THREAD

**Issue by yo-shari** [FastLED/FastLED#453]
Hello, I'm new to using this library. I was that there is a commit message that operator= was fixed in pixelset.h however when I am trying to compile the blink example I get an error with that exact line.

![image](https://cloud.githubusercontent.com/assets/15252485/26428433/7d2550c0-4096-11e7-8f04-8e1a34e1aed9.png)

**Comment by focalintent** [comment]
Have you gotten the most recent version of the library from GitHub?

**Comment by yo-shari** [comment]
Yes, I downloaded the library earlier today. Then again just now.

**Comment by focalintent** [comment]
What happens if you try with a more recent version of Arduino?  This is the first time i've seen this error pop up - and I stopped doing work/testing with the 1.0.x versions of arduino a year or more ago - the readme even states this:

IMPORTANT NOTE: For AVR based systems, avr-gcc 4.8.x is supported and tested. This means Arduino 1.6.5 and later.

**Comment by yo-shari** [comment]
I was using a mac and I got it working using a PC

**Comment by marmilicious** [comment]
What version of Arduino is on the PC?

**Comment by yo-shari** [comment]
The PC must have a new version because it wasn't the right version on the mac. My bad, thank you for  helping me out though. I got the LEDs working!
