### ISSUE TITLE
bitswap.h：No such file or directory

### ISSUE THREAD

**Issue by lianxingjie** [FastLED/FastLED#473]
When I compile fastled, the following error occurs.
$ make
g++  -D ESP8266   -c -o wiring.o wiring.cpp
In file included from platforms.h:24:0,
                 from FastLED.h:55,
                 from wiring.cpp:2:
platforms/esp/8266/fastled_esp8266.h:2:21: 致命错误：bitswap.h：No such file or directory
编译中断。
make: *** [<内置>：wiring.o] 错误 1

**Comment by focalintent** [comment]
FastLED isn't really designed for building from the command line quite like that - you have to make sure to set up include directories and such properly so that includes are found, which is beyond the scope of an issue here -- but basically, make sure that you have whatever directory FastLED.h is in in your include search path.  You might need to explicitly have ```-I .``` at the very least if you have FastLED checked out into the directory where you have wiring.cpp.

I have some header file re-arrangement that i'd like to do that might clean this up, but this should help you out in the meantime.
