### ISSUE TITLE
Separate all effects as a second platform independent library.

### ISSUE THREAD

**Issue by hetii** [FastLED/FastLED#479]
Hello :)
I have some idea to separate all effects as separate project written in C.
It should be written totally as a platform independent code and linked as a library for project like FastLED or any other one.

By that way people could commit their effects and all different projects use such "led layout language" at the end.

Let me know what do you think about this idea.

**Comment by focalintent** [comment]
Sounds like a fantastic project idea!  Let me know when you starting working on it and set up a repo for it, and we'll be happy to link to it.  (Note that something like this is way outside the scope of what we've got planned for FastLED - I do have a private library that I use for effects building, but it's very unstable, and regularly gets thrown away and rewritten - but it turns out that while it's pretty straight forward to have a library that allows you to address/set LEDs, the needs and desires of people building led projects and doing animations and such are wildly different enough that having a single pattern/effect library that would be usable by everyone in the ways they need it would be quite a complex undertaking - even as my projects evolve from project to project, I find the effects library code i've tried writing in the past isn't applicable to a new project, hence it getting thrown away and rewritten).
