### ISSUE TITLE
FASTLED_ALLOW_INTERRUPTS for Teensy + typo?

### ISSUE THREAD

**Issue by NicoHood** [FastLED/FastLED#488]
https://github.com/FastLED/FastLED/blob/06521a48e9febdea8dbf3a5520620a578c051f95/platforms/avr/led_sysdefs_avr.h#L22-L26

1. Does this mean if you are using the teensy2 core, then interrupts can be enabled, as the code is better? If yes, why dont you do that? Or does this statement mean, that its untested but will more likely work on a teensy2?

2.  `teensy2 vs. other arm platforms` is possibly a typo and you mean `avr`?

**Comment by focalintent** [comment]
1. No - it was a note to myself that it might have been possible to make it work in the future.
2. it is a typo

but neither of the above matter, because it turns out that even on the teensy 2 allowing interrupts is a bad idea and I yanked all the relevant code out of the avr asm, so even if you set FASTLED_ALLOW_INTERRUPTS to 1 on an avr platform it would have no effect.
