### ISSUE TITLE
CLEDController.showLeds display wrong color

### ISSUE THREAD

**Issue by darkovuj** [FastLED/FastLED#572]
If you set LED color to white (eg RGB: 15, 15, 15) and fade it to black you will get wrong color when you update leds with ledController->showLeds(). When value for each color on led is 1 every even led will have values for R and B of 1 and G value will be 0. On odd leds G value will be 1 and R and B 0. 
If you use FastLED.show() output is correct.

I'm using fastled version3.1.6

`
#define FASTLED_ESP8266_RAW_PIN_ORDER
#define FASTLED_ESP8266_NODEMCU_PIN_ORDER
#define FASTLED_ESP8266_D1_PIN_ORDER
#define FASTLED_ALLOW_INTERRUPTS 0

#include <FastLED.h>

CRGB leds[8];
CLEDController *_ledController;

void setup()
{
	_ledController = &FastLED.addLeds <WS2812B,  2, GRB>(leds, 8);
}

void loop()
{
	fill_solid(leds, 8, CRGB(15,15,15));

	while (leds[0].r != 0) {
		fadeToBlackBy(leds, 8, 1);

		//_ledController->showLeds(); // not correct output

		FastLED.show();		// correct output

		delay(500);
	}
}
`

**Comment by focalintent** [comment]
You are seeing dithering, and this is how it is supposed to be working.  This is because FastLED.show contains logic to disable the dithering engine when the frame rate is below 100, while the individual controller show method doesn’t.   You should disable dithering on the controllers individually if you don’t want it.
