### ISSUE TITLE
Wrong color values mapped in HSV 

### ISSUE THREAD

**Issue by parmarravi** [FastLED/FastLED#576]
Thank you for Fast led library.
The Color in HSV is mapped to 255,255,255 however in reality the HSV color is  360,100,100 .How to use the HSV color in fastLed?

**Comment by kriegsman** [comment]
FastLED uses an 8-bit native scale, instead of the 360º/100%/100% scale.  There's more written about it here, including some illustrations https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors

We like to use this github bug tracker just for bugs in the library itself.  For general discussions, help, and how-to, check out the FastLED discussion group here: http://fastled.io/+
Thanks for using the library!
