### ISSUE TITLE
Use of n/32 instead of n/64 for APA102 in endBoundary()?

### ISSUE THREAD

**Issue by ssilverman** [FastLED/FastLED#616]
https://github.com/FastLED/FastLED/blob/385a56fa6318c8928c60042ddb78d65db2811876/chipsets.h#L163

This uses n/32. Curious why this doesn't use n/64? I was under the impression that there needs to be one extra '1' per 2 pixels.
See: https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/

There's no harm in leaving it as-is, but we can possibly get away with sending less data here.

**Comment by focalintent** [comment]
Because I had runs of strips where n/64 wasn’t enough (possible early apa102 clones? Or bad batches ¯\_(ツ)_/¯) - and the difference in data that we are talking about here is minor enough that I’d rather have things always work.  And specifically, wanted things working in my projects where I was using the 102s
