### ISSUE TITLE
millis() is faster than real time with arduino and ws2812

### ISSUE THREAD

**Issue by peterloves** [FastLED/FastLED#675]
are there any solution for that millis() = real time, in arduino uno?

**Comment by focalintent** [comment]
No - the problem is writing out ws2811 data requires disabling interrupts - advancing the clock requires an interrupt firing.  FastLED attempts to adjust the clock after it has finished writing the data out, but it is approximate.  If you need accurate time you need to either switch to something like apa102 that will not disable interrupts, switch to one of the arm or esp based platforms that don’t disable interrupts, or get an external RTC (real time clock) and use that for your time source.
