### ISSUE TITLE
BUG: Chipset.h has multiple invalid timing data

### ISSUE THREAD

**Issue by henrygab** [FastLED/FastLED#799]
I've a large-ish number of fixes to chipset.h.  Issues include:
* Timings are out-of-spec compared to chipset datasheet
* Header comments are not aligned with values used
* Some clockless chips signals need to be inverted, but are not defined as such

### Questions:
1. Would you prefer one issue per chipset? (might simplify discussions, tracking)
2. Would you prefer one PR per chipset? (might simplify testing / verification to one chipset at a time)
3. Would you prefer one massive PR that addresses all the timing issues and protocols at once?  (would still use one commit per chipset, for easier review of changes)
4. Is there a branch or other location you store datasheets for the supported LED chipsets?  Do you want datasheets?

Thanks!

**Comment by focalintent** [comment]
So the problem with data sheets is that sometimes there are multiple datasheets with different sets of timings (I have three different timings in three different WS2811 datasheets, for example :) 

Also while there is a flag for it FastLED doesn’t actually fully support inverted signs chipsets right now.  I’ll take a look at a PR - but there aren’t many issues that are ultimately caused by timing being off -
and so if he wary of taking a PR that is just based on the chipsets without also being in a position to test/verify that said chipsets are in fact working with the newly submitted timings.  

My solution for this is going to be to leave the existing timings alone for now, and making timing specification a lot easier and a lot more flexible in the future for folks to play with.

**Comment by henrygab** [comment]
OK.  I totally get the different values from different datasheets, having tried to compare different vendors' stuff before … the numbers can have … flexible meanings.  I'll still make a PR with the more obvious errors.

Do you have a repo for the LED datasheets?
