### ISSUE TITLE
FastLED ESP32 hardware engines usage

### ISSUE THREAD

**Issue by BlumAmir** [FastLED/FastLED#815]
Hi, 

I am trying to use the hardware engines in the ESP32 with FastLED to offload the serial Tx work so calculations for next frame can take place, I understand there is both RMT and I2S engines.

Using version 3.2.6, when measuring the time it takes FastLED.show() I expect to see low times of 0-2 ms but get 18-19 ms for 600 leds. Side note, version 3.2.8 shows 96 ms.

test code:
`
#define FASTLED_ESP32_I2S true
//#define FASTLED_RMT_MAX_CHANNELS 1
#include "FastLED.h"
#include <time.h>

#define NUM_LEDS 600

#define DATA_PIN 18

// Define the array of leds
CRGB leds[NUM_LEDS];

unsigned long timeBefore, timeAfter, timeDiff;

void setup() {
  Serial.begin(115200);
  FastLED.addLeds<WS2812, DATA_PIN, RGB>(leds, NUM_LEDS);
}

void loop() {
  leds[0] = CRGB::Red;
  delay(50); // simulate LED color calculations
  timeBefore = millis();
  FastLED.show();
  timeAfter = millis();
  timeDiff = timeAfter - timeBefore;
  Serial.println(timeDiff);
}
`

Am I missing some required definition?

Tested on:
ESP32 devkitv1 clone board
PlatformIO arduino framework

**Comment by focalintent** [comment]
At a minimum - this is a dup of #318 (that's what's causing the 92ms timings for 3.2.8)

As for the times for calling show - I believe the I2S code is synchronous, which is to say that show won't return until it has finished writing out all the data.  I don't recall offhand with the RMT driver - so the 18-19ms is correct.

On the esp32 the hardware support is more about making sure that interrupts can run so that things like wifi/bluetooth handling can still occur without any issues.  The output isn't a true background output like, say, the OctoWS2811 on the teensy is.  (There's a variety of reasons that this is the case, not the least of which being the amount of memory that would be necessary to keep the pre-prepared data entirely in memory, vs. the way this code works which is continually filling/switch between two smaller buffers of data for the hardware engines to drive out).
