### ISSUE TITLE
Clock timings differ significantly between 8MHz/16MHz/24MHz CPUs and  and 

### ISSUE THREAD

**Issue by henrygab** [FastLED/FastLED#829]
There appears to be significant differences in timings for some chipsets, depending on which CPU is being used to drive the LEDs.  Here's a table to help see the differences:

Capital T1/T2/T3 refer to 8MHz/16MHz/24MHz clocks, which use fixed multiples of 125ns.
Lowercase t1/t2/t3 refer to definition listing nanoseconds explicitly.

Controller | T1 | T2 | T3 | t1 | t2 | t3 | Comment
--- | --- | --- | --- | --- | --- | --- | ---
WS2811Controller400Khz | [**500** ](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L482)| **1250** | 750 | [**800**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L575) | **800** | 900 | See T1/T2 vs. t1/t2
WS2811Controller800Khz | [375](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L476) | **500** | **375** | [320](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L563) | **320** | **640** | Second and third swapped?
WS2813Controller | [375](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L479) | **500** | **375** | [320](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L567) | **320** | **640** | Second and third swapped?
TM1829Controller800Khz | [250](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L512) | **625** | **375** | [340](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L582) | **340** | **550** | Second and third swapped?
TM1809Controller800Khz | [**250**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L506) | 625 | 375 | [**350**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L559) | 350 | 450 | Likely OK?
GW6205Controller800Khz | [**250**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L518) | 500 | 500 | [**400**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L539) | 400 | 400 |  Likely OK?
UCS1903BController800Khz | [**250**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L497) | 500 | 500 | [**400**](https://github.com/FastLED/FastLED/blob/c563be6a37d9d561eb53f49a233fafd5c8c8b44a/chipsets.h#L547) | 450 | 450 | Likely OK?

I realize that many controllers may be lax in their timings, that the 125ns increments are somewhat limiting, and that it may be more instructive to look at `{ T1, T1+T2, T1+T2+T3}` as the three values.  Even so, the above strongly suggests changing CPUs could change timing enough to change from working to non-working (or vice versa).

I haven't got all these controllers.  Is it worth looking into?  Would it be worth at least adding comments to the lines defining these controllers to highlight these differences?

**Comment by focalintent** [comment]
No - it isn't worth looking into or changing.  With these controllers the important bit is T1 and the sum of T1+T2+T3.  If T1 is too long everything gets read as a 1 (yay, bright white, overdrawing your power supply!) - and if the sum of T1+T2+T3 is too short, then all the data just ends up randomly and weirdly corrupted.  

In the cases where things look like they're a bit swapped, that was because of the way the asm is laid out at 8Mhz (and in some cases, 16), in order to keep things sane/workable and give me enough clock cycles to do things, on these systems I decided to stretch the "time" for a 1 bit (e.g. swapping T2 and T3) a little to give me some more flexibility - while opting for keeping the exact timings as close as possible to the data sheet definitions on the higher clock rate systems.

Of course, this is all in the process of getting overhauled, including the way these chipsets are defined and implemented - so I'm not putting a lot of work into this existing setup/code/documentation right now.

(Also - after what happened last time with the nrf52 submission - I'm not taking any more changes that come close to touching chipsets.h and the clockless chips without confirmation of testing across chipsets and across platforms)
